name: Build ANGLE

on:
  push:
    branches: master

jobs:
  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth 1
          export PATH=$(pwd)/depot_tools:$PATH
          python scripts/bootstrap.py
          gclient sync
          ./build/install-build-deps.sh
          gn gen out/Release
          echo "is_debug = false\ndcheck_always_on = false" >> out/Release/args.gn
          autoninja -C out/Release
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libs-linux
          path: out/Release/lib*.so